--CREACION DE USUARIO
CREATE USER 'kevinooo'@'localhost' IDENTIFIED BY '123456';
--ELIMINAR USUARIO
 DROP USER 'kevinooo'@'localhost';
 -- DAR TODOS LOS PRIVILEGIOS
 GRANT ALL PRIVILEGES ON *.* TO 'kevinooo'@'localhost';
 --ACTIVAMOS LOS PRIVILEGIOS
 FLUSH PRIVILEGES;